import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ToastContainer, toast } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import Providers from "./Redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Officing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex bg-[#E6F3F5]">
            <div className=" max-w-[272px] bg-white rounded-se-2xl">
              <Sidebar />
            </div>
            <div className="bg-[#E3EFE0] w-[83%] p-10">{children}</div>
            <ToastContainer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
